// Auto-generated by supersave-fetcher.ts
// Last updated: 2025-11-09T18:57:38.509Z
// Source: SuperSave.pt API

export type Product = {
  id: string;
  name: string;
  imageUrl: string;
  store: string;
  price: number;
  category?: string;
  brand?: string;
};

const products: Product[] = [
  {
    "id": "supersave-17269660",
    "name": "Néctar Laranja do Algarve emb. 3 x 1 lt",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwc3319e31/images/col/843/8433315-frente.jpg?sw=500&sh=500",
    "store": "Continente",
    "price": 4.99,
    "category": "Bebidas",
    "brand": "Compal Origens"
  },
  {
    "id": "supersave-17269334",
    "name": "Água Tónica 1.0 L",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw81b6349f/images/large/959578_7fb82644621ec26203bb9dadf4ba336f.png?sw=421",
    "store": "Pingo Doce",
    "price": 1.99,
    "category": "Bebidas",
    "brand": "Royal Bliss"
  },
  {
    "id": "supersave-17265806",
    "name": "Refrigerante com Gás Cola Zero Açúcar Zero Cafeína Lata Pack 6 0.33 L",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dwd15bd8d3/images/large/720921_5ac720a2b230700b5c7855687e6a0635.jpg?sw=421",
    "store": "Pingo Doce",
    "price": 4.79,
    "category": "Bebidas",
    "brand": "Coca-Cola"
  },
  {
    "id": "supersave-17265797",
    "name": "Refrigerante com Gás Cola Zero Mini Lata Pack 12 0.15 L",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dwc68ee425/images/large/869636_fe0f573afd459af8c4d7b1221ba9bf41.jpg?sw=421",
    "store": "Continente",
    "price": 7.2,
    "category": "Bebidas",
    "brand": "Coca-Cola"
  },
  {
    "id": "supersave-17265796",
    "name": "Refrigerante com Gás Cola Zero Açúcar Zero Cafeína 1.75 L",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dwc27122a6/images/large/922053_b835637784bc4dfd850062f855483565.png?sw=421",
    "store": "Auchan",
    "price": 1.85,
    "category": "Bebidas",
    "brand": "Coca-Cola"
  },
  {
    "id": "supersave-17265795",
    "name": "Refrigerante Com Gás Coca-Cola Zero Cafeína E Zero Açúcar 12X0.15L",
    "imageUrl": "https://www.auchan.pt/dw/image/v2/BFRC_PRD/on/demandware.static/-/Sites-auchan-pt-master-catalog/default/dw5e772306/images/hi-res/001149659.jpg?sw=250&sh=250&sm=fit&bgcolor=FFFFFF",
    "store": "Continente",
    "price": 7.2,
    "category": "Bebidas",
    "brand": "COCA-COLA"
  },
  {
    "id": "supersave-17265794",
    "name": "Refrigerante com Gás Cola Zero Açúcar Zero Cafeína 1.0 L",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw04c95866/images/large/952997_7e924aacc49c7388302d8651e8666ebc.png?sw=421",
    "store": "Pingo Doce",
    "price": 1.19,
    "category": "Bebidas",
    "brand": "Coca-Cola"
  },
  {
    "id": "supersave-17265793",
    "name": "Refrigerante Com Gás Coca-Cola Zero Cafeína E Zero Açúcar 0.33L",
    "imageUrl": "https://www.auchan.pt/dw/image/v2/BFRC_PRD/on/demandware.static/-/Sites-auchan-pt-master-catalog/default/dw0d8a3128/images/hi-res/001114968.jpg?sw=250&sh=250&sm=fit&bgcolor=FFFFFF",
    "store": "Auchan",
    "price": 0.85,
    "category": "Bebidas",
    "brand": "COCA-COLA"
  },
  {
    "id": "supersave-17265787",
    "name": "Refrigerante Com Gás Coca-Cola Zero Açúcar Vidro 4X0.20L",
    "imageUrl": "https://www.auchan.pt/dw/image/v2/BFRC_PRD/on/demandware.static/-/Sites-auchan-pt-master-catalog/default/dw016023dd/images/hi-res/003211869.jpg?sw=250&sh=250&sm=fit&bgcolor=FFFFFF",
    "store": "Continente",
    "price": 3,
    "category": "Bebidas",
    "brand": "COCA-COLA"
  },
  {
    "id": "supersave-17265781",
    "name": "Refrigerante Com Gás Coca-Cola Zero Cafeína 1L",
    "imageUrl": "https://www.auchan.pt/dw/image/v2/BFRC_PRD/on/demandware.static/-/Sites-auchan-pt-master-catalog/default/dw171f4814/images/hi-res/000827415.jpg?sw=250&sh=250&sm=fit&bgcolor=FFFFFF",
    "store": "Continente",
    "price": 1.35,
    "category": "Bebidas",
    "brand": "COCA-COLA"
  },
  {
    "id": "supersave-17265779",
    "name": "Refrigerante com Gás Cola Zero Lata Pack 6 0.33 L",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw989ddc7d/images/large/720920_d246216c6be28ac2ff680de3ca278cb0.jpg?sw=421",
    "store": "Pingo Doce",
    "price": 4.79,
    "category": "Bebidas",
    "brand": "Coca-Cola"
  },
  {
    "id": "supersave-17265778",
    "name": "Refrigerante Com Gás Coca-Cola Zero Açúcar Lata 0.33L",
    "imageUrl": "https://www.auchan.pt/dw/image/v2/BFRC_PRD/on/demandware.static/-/Sites-auchan-pt-master-catalog/default/dwdd514d06/images/hi-res/001115018.jpg?sw=250&sh=250&sm=fit&bgcolor=FFFFFF",
    "store": "Auchan",
    "price": 0.85,
    "category": "Bebidas",
    "brand": "COCA-COLA"
  },
  {
    "id": "supersave-17270498",
    "name": "Chocolate Branco Ferrero Rocher 90 G",
    "imageUrl": "https://www.auchan.pt/dw/image/v2/BFRC_PRD/on/demandware.static/-/Sites-auchan-pt-master-catalog/default/dw9368f238/images/hi-res/003576735.jpg?sw=250&sh=250&sm=fit&bgcolor=FFFFFF",
    "store": "Continente",
    "price": 2.49,
    "category": "Laticínios",
    "brand": "FERRERO ROCHER"
  },
  {
    "id": "supersave-17270497",
    "name": "Chocolate Ferrero Rocher Dark 90 G",
    "imageUrl": "https://www.auchan.pt/dw/image/v2/BFRC_PRD/on/demandware.static/-/Sites-auchan-pt-master-catalog/default/dw1fe11e44/images/hi-res/003430425.jpg?sw=250&sh=250&sm=fit&bgcolor=FFFFFF",
    "store": "Continente",
    "price": 2.49,
    "category": "Laticínios",
    "brand": "FERRERO ROCHER"
  },
  {
    "id": "supersave-17270479",
    "name": "Leite UHT Magro emb. 1 lt",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw775a83b3/images/col/816/8163567-frente.png?sw=500&sh=500",
    "store": "Continente",
    "price": 0.87,
    "category": "Laticínios",
    "brand": "Gresso"
  },
  {
    "id": "supersave-17270478",
    "name": "Leite UHT Inteiro emb. 6 x 1 lt",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw9584bec7/images/col/221/2210969-frente.jpg?sw=500&sh=500",
    "store": "Continente",
    "price": 1.09,
    "category": "Laticínios",
    "brand": "Gresso"
  },
  {
    "id": "supersave-17270477",
    "name": "Leite UHT Magro emb. 1lt",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw7c8eb40c/images/col/244/2448046-direito.png?sw=500&sh=500",
    "store": "Continente",
    "price": 0.88,
    "category": "Laticínios",
    "brand": "Nova Açores"
  },
  {
    "id": "supersave-17270475",
    "name": "Leite UHT Magro emb. 3 x 200 ml",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw5ebb8db0/images/col/706/7062997-hero.jpg",
    "store": "Continente",
    "price": 0.94,
    "category": "Laticínios",
    "brand": "Continente Equilíbrio"
  },
  {
    "id": "supersave-17270466",
    "name": "Leite UHT Gordo emb. 1 lt",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwe29e18b5/images/col/692/6927108-hero.jpg",
    "store": "Continente",
    "price": 0.99,
    "category": "Laticínios",
    "brand": "Continente"
  },
  {
    "id": "supersave-17270465",
    "name": "Leite UHT Magro emb. 1 lt",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw6a5d60b5/images/col/687/6879889-hero.jpg",
    "store": "Continente",
    "price": 0.86,
    "category": "Laticínios",
    "brand": "Continente Equilíbrio"
  },
  {
    "id": "supersave-17270464",
    "name": "Leite Magro Açores emb. 1 lt",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw6c76caae/images/col/692/6927375-frente.jpg",
    "store": "Continente",
    "price": 0.87,
    "category": "Laticínios",
    "brand": "Continente Equilíbrio"
  },
  {
    "id": "supersave-17270463",
    "name": "Leite UHT Magro emb. 1 lt",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw6966ee8d/images/col/221/2210957-frente.jpg",
    "store": "Continente",
    "price": 0.88,
    "category": "Laticínios",
    "brand": "Agros"
  },
  {
    "id": "supersave-17270398",
    "name": "Leite UHT Meio Gordo emb. 12 x 1 lt",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwd18c4d36/images/col/802/8020279-frente.jpg?sw=180&sh=180",
    "store": "Continente",
    "price": 13,
    "category": "Laticínios",
    "brand": "Matinal"
  },
  {
    "id": "supersave-17270294",
    "name": "Chocolate Milka Bubbly 90G",
    "imageUrl": "https://www.auchan.pt/dw/image/v2/BFRC_PRD/on/demandware.static/-/Sites-auchan-pt-master-catalog/default/dw52bb8e7f/images/hi-res/000546617.jpg?sw=250&sh=250&sm=fit&bgcolor=FFFFFF",
    "store": "Continente",
    "price": 2.49,
    "category": "Laticínios",
    "brand": "MILKA"
  },
  {
    "id": "supersave-17270358",
    "name": "Bolachas Belgas 0.22 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw485df8db/images/large/833698_aa7ca1bada28f2c7c50496cb90fb05a0.jpg?sw=421",
    "store": "Continente",
    "price": 1.49,
    "category": "Bolachas",
    "brand": "Saborosa"
  },
  {
    "id": "supersave-17270356",
    "name": "Bolachas de Manteiga com Cereais Dinosaurus 0.185 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dwf363a101/images/large/629663_1242315b18e40ed820313f211a7670b7.jpg?sw=421",
    "store": "Continente",
    "price": 1.69,
    "category": "Bolachas",
    "brand": "Artiach"
  },
  {
    "id": "supersave-17270355",
    "name": "Bolachas de Manteiga Butter Cookies 0.454 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw914ff699/images/large/874242_a14508f156b9ed3776944b14bf0d4e08.jpg?sw=421",
    "store": "Pingo Doce",
    "price": 3.89,
    "category": "Bolachas",
    "brand": "Pingo Doce"
  },
  {
    "id": "supersave-17270345",
    "name": "Bolachas de Manteiga 0.168 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw3b8a1817/images/large/753574_85d94095444ca643f9d9fa2152832677.jpg?sw=421",
    "store": "Continente",
    "price": 1.49,
    "category": "Bolachas",
    "brand": "Triunfo"
  },
  {
    "id": "supersave-17270287",
    "name": "Bolachas de Chocolate de Leite Mikado 0.075 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dwdf9047a5/images/large/597531_ac91ac39b837ebd2a93a3a808ec38600.jpg?sw=421",
    "store": "Pingo Doce",
    "price": 1.99,
    "category": "Bolachas",
    "brand": "LU"
  },
  {
    "id": "supersave-17269828",
    "name": "Bolachas Recheadas com Chocolate e Avelãs 0.304 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw54cc44e3/images/large/928200_93163045fc130cbb6c75c91e27b4c0cb.jpg?sw=421",
    "store": "Continente",
    "price": 4.79,
    "category": "Bolachas",
    "brand": "Nutella"
  },
  {
    "id": "supersave-17268075",
    "name": "Bolachas Mini Cookies Zero Açúcar 0.12 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw467d1a13/images/large/745615_bcf35f56392aa7b7f1a9483400c6ca19.jpg?sw=421",
    "store": "Continente",
    "price": 2.49,
    "category": "Bolachas",
    "brand": "Artiach"
  },
  {
    "id": "supersave-17267958",
    "name": "Bolacha 5 Cereais e Framboesa sem Açúcar emb. 160 gr (4 un)",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw29d7f43b/images/col/735/7358209-hero.jpg",
    "store": "Continente",
    "price": 2.49,
    "category": "Bolachas",
    "brand": "Continente Equilíbrio"
  },
  {
    "id": "supersave-17267955",
    "name": "Bolachas Chocolate e Cacau sem Açúcar emb. 160 gr (4 un)",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw6cd37e77/images/col/735/7358218-hero.jpg",
    "store": "Continente",
    "price": 2.49,
    "category": "Bolachas",
    "brand": "Continente Equilíbrio"
  },
  {
    "id": "supersave-17267952",
    "name": "Bolachas Pequeno Almoço Cereais sem Açúcar emb. 300 gr (6 un)",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw666eb26f/images/col/736/7361214-frente.jpg",
    "store": "Continente",
    "price": 1.99,
    "category": "Bolachas",
    "brand": "Continente"
  },
  {
    "id": "supersave-17267951",
    "name": "Bolachas Chai e Gengibre sem Açúcar emb. 160 gr (4 un)",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwc2197a0e/images/col/735/7358217-hero.jpg",
    "store": "Continente",
    "price": 2.49,
    "category": "Bolachas",
    "brand": "Continente Equilíbrio"
  },
  {
    "id": "supersave-17267945",
    "name": "Bolachas Mini Cookies Zero Açúcar 0.12 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw467d1a13/images/large/745615_bcf35f56392aa7b7f1a9483400c6ca19.jpg?sw=421",
    "store": "Continente",
    "price": 2.49,
    "category": "Bolachas",
    "brand": "Artiach"
  },
  {
    "id": "supersave-17270337",
    "name": "Iogurte Proteico, Manteiga Amendoim e Banana 0.16 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw1a8936b6/images/large/909388_97c743bc23494bbe4d041c8e2af3df1c.jpg?sw=421",
    "store": "Continente",
    "price": 1.29,
    "category": "Iogurtes",
    "brand": "Yopro"
  },
  {
    "id": "supersave-17270334",
    "name": "Iogurte Grego Mythos Manteiga de Amendoim emb. 460 gr (4 un)",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw7fad4a05/images/col/843/8430707-frente.jpg?sw=500&sh=500",
    "store": "Continente",
    "price": 1.49,
    "category": "Iogurtes",
    "brand": "Continente"
  },
  {
    "id": "supersave-17270044",
    "name": "Dose Fruta Maçã, Banana, Laranja e Ananás Kids +3 Anos 0.11 L",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dwed757881/images/large/985619_845be1750adf56ade259dcbd20882d03.png?sw=421",
    "store": "Pingo Doce",
    "price": 0.69,
    "category": "Iogurtes",
    "brand": "Compal"
  },
  {
    "id": "supersave-17269823",
    "name": "Yofu Alpro Natural Estilo Skyr 400G",
    "imageUrl": "https://www.auchan.pt/dw/image/v2/BFRC_PRD/on/demandware.static/-/Sites-auchan-pt-master-catalog/default/dwe3937467/images/hi-res/003156300.jpg?sw=250&sh=250&sm=fit&bgcolor=FFFFFF",
    "store": "Continente",
    "price": 2.99,
    "category": "Iogurtes",
    "brand": "ALPRO"
  },
  {
    "id": "supersave-17269819",
    "name": "Iogurte Skyr Natural emb. 150 gr",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw91304262/images/col/627/6275776-cima.jpg",
    "store": "Continente",
    "price": 0.65,
    "category": "Iogurtes",
    "brand": "Continente Equilíbrio"
  },
  {
    "id": "supersave-17269659",
    "name": "Dose Fruta Maçã, Banana, Laranja e Ananás Kids +3 Anos 0.11 L",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dwed757881/images/large/985619_845be1750adf56ade259dcbd20882d03.png?sw=421",
    "store": "Pingo Doce",
    "price": 0.69,
    "category": "Iogurtes",
    "brand": "Compal"
  },
  {
    "id": "supersave-17266797",
    "name": "Iogurte Líquido Reduz Colesterol Frutos Exóticos Pack 6 0.6 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dwc5f644a7/images/large/513365003_1ef0fb560d29bfa46ea3f0b8f192e073.jpg?sw=421",
    "store": "Continente",
    "price": 3.09,
    "category": "Iogurtes",
    "brand": "Danacol Danone"
  },
  {
    "id": "supersave-17266796",
    "name": "Iogurte Líquido Bífidus Morango Pack 12 1.2 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw37d4cc56/images/large/697065_7023f7abea6aacb9b400c6ba7fbb83ab.jpg?sw=421",
    "store": "Continente",
    "price": 5.99,
    "category": "Iogurtes",
    "brand": "Danacol Danone"
  },
  {
    "id": "supersave-17266795",
    "name": "Iogurte Líquido Reduz Colesterol Aveia Pack 12 1.2 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw8699545a/images/large/966748_7cd2c16ab90e055a2511fa09ef7ed616.jpg?sw=421",
    "store": "Continente",
    "price": 5.99,
    "category": "Iogurtes",
    "brand": "Danacol Danone"
  },
  {
    "id": "supersave-17266794",
    "name": "Iogurte Líquido Reduz Colesterol Noz Pack 6 0.6 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw67a7c104/images/large/513365008_2fb1e5e04844ef8144d2719b4e3a8738.jpg?sw=421",
    "store": "Continente",
    "price": 3.09,
    "category": "Iogurtes",
    "brand": "Danacol Danone"
  },
  {
    "id": "supersave-17269918",
    "name": "Bebida de Cereais Solúvel Península 0.22 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dwfdfda250/images/large/963165_c2b8cbfbf63248359f1f298fd67459a8.jpg?sw=421",
    "store": "Continente",
    "price": 2.59,
    "category": "Cereais",
    "brand": "Delta"
  },
  {
    "id": "supersave-17268661",
    "name": "Bebida de Cereais Solúvel Península 0.22 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dwfdfda250/images/large/963165_c2b8cbfbf63248359f1f298fd67459a8.jpg?sw=421",
    "store": "Continente",
    "price": 2.59,
    "category": "Cereais",
    "brand": "Delta"
  },
  {
    "id": "supersave-17268397",
    "name": "Bebida de Cereais Solúvel 0.2 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw105f4be1/images/large/974032_df555e7c601e685f3a796b63372f105f.jpeg?sw=421",
    "store": "Continente",
    "price": 2.89,
    "category": "Cereais",
    "brand": "Tofina"
  },
  {
    "id": "supersave-17268396",
    "name": "Cevada Cem Porcento Grão 500G",
    "imageUrl": "https://www.auchan.pt/dw/image/v2/BFRC_PRD/on/demandware.static/-/Sites-auchan-pt-master-catalog/default/dwcff67d44/images/hi-res/002932592.jpg?sw=250&sh=250&sm=fit&bgcolor=FFFFFF",
    "store": "Auchan",
    "price": 2.09,
    "category": "Cereais",
    "brand": "CEM PORCENTO"
  },
  {
    "id": "supersave-17268393",
    "name": "Flocos Salutem Cevada Integrais Tostados 250G",
    "imageUrl": "https://www.auchan.pt/dw/image/v2/BFRC_PRD/on/demandware.static/-/Sites-auchan-pt-master-catalog/default/dw87c60c5a/images/hi-res/000428041.jpg?sw=250&sh=250&sm=fit&bgcolor=FFFFFF",
    "store": "Auchan",
    "price": 1.83,
    "category": "Cereais",
    "brand": "SALUTEM"
  },
  {
    "id": "supersave-17268386",
    "name": "Cevada Solúvel 0.2 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw9a545f4c/images/large/764867_228567677ff88dc60ab5124597dfbf0e.jpg?sw=421",
    "store": "Auchan",
    "price": 2.65,
    "category": "Cereais",
    "brand": "Delta"
  },
  {
    "id": "supersave-17265260",
    "name": "Granola Cem Porcento Fruta E Canela 350G",
    "imageUrl": "https://www.auchan.pt/dw/image/v2/BFRC_PRD/on/demandware.static/-/Sites-auchan-pt-master-catalog/default/dw57dd052e/images/hi-res/002138621.jpg?sw=250&sh=250&sm=fit&bgcolor=FFFFFF",
    "store": "Auchan",
    "price": 3.89,
    "category": "Cereais",
    "brand": "CEM PORCENTO"
  },
  {
    "id": "supersave-17264486",
    "name": "Mix Pequeno Almoço Shine Aveia Amêndoa E Canela Bio 300G",
    "imageUrl": "https://www.auchan.pt/dw/image/v2/BFRC_PRD/on/demandware.static/-/Sites-auchan-pt-master-catalog/default/dw90fd4732/images/hi-res/003094954.jpg?sw=250&sh=250&sm=fit&bgcolor=FFFFFF",
    "store": "Continente",
    "price": 4.99,
    "category": "Cereais",
    "brand": "SHINE"
  },
  {
    "id": "supersave-17270325",
    "name": "Barra Proteica Manteiga de Amendoim 0.065 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dweb634af3/images/large/976785_f034efd191dfdbb7b5315dfd347d41b8.png?sw=421",
    "store": "Continente",
    "price": 1.79,
    "category": "Snacks",
    "brand": "Prozis"
  },
  {
    "id": "supersave-17270275",
    "name": "Snack para Gato de Galinha e Pato 0.06 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dwac6a7d22/images/large/864902_b9b3ac40da56aa8a85c96ff991fa8500.jpg?sw=421",
    "store": "Continente",
    "price": 2.29,
    "category": "Snacks",
    "brand": "Catisfactions"
  },
  {
    "id": "supersave-17269997",
    "name": "Bolsa Multifrutas 0.36 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw206d2288/images/large/946304_b1ca66047c56508d82b130a4aa03e4cc.png?sw=421",
    "store": "Continente",
    "price": 2.54,
    "category": "Snacks",
    "brand": "GoGo squeeZ"
  },
  {
    "id": "supersave-17269996",
    "name": "Bolsa de Fruta, Aveia e Curcuma 0.12 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dwae789ab4/images/large/930607_d8035a88a1f677d6db55472eff1bd1e9.png?sw=421",
    "store": "Pingo Doce",
    "price": 0.99,
    "category": "Snacks",
    "brand": "Pingo Doce"
  },
  {
    "id": "supersave-17269990",
    "name": "Bolsa de Fruta e Chia 0.12 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw342f8b87/images/large/930606_6e006d7f8b5a6466dca6d442bc6cc4ee.jpeg?sw=421",
    "store": "Pingo Doce",
    "price": 0.99,
    "category": "Snacks",
    "brand": "Pingo Doce"
  },
  {
    "id": "supersave-17269989",
    "name": "Bolsa de Fruta Banana Maçã e Morango 0.09 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw60ee9fd2/images/large/955642_34d7e58967d87d4046acbc680f7667dd.jpg?sw=421",
    "store": "Continente",
    "price": 0.65,
    "category": "Snacks",
    "brand": "Nestlé"
  },
  {
    "id": "supersave-17269988",
    "name": "Bolsa de Fruta Maçã e Banana 0.36 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw12846034/images/large/887363_1d3c252aaa8692ceece1f887c9ed10e5.jpg?sw=421",
    "store": "Continente",
    "price": 2.54,
    "category": "Snacks",
    "brand": "GoGo squeeZ"
  },
  {
    "id": "supersave-17269987",
    "name": "Bolsas de Fruta Maçã e Pera 0.36 Kg",
    "imageUrl": "https://www.pingodoce.pt/dw/image/v2/BLJJ_PRD/on/demandware.static/-/Sites-pingo-doce-master/default/dw54baceae/images/large/920856_754c7c46dd0d16cfbee831606e0ea36b.jpg?sw=421",
    "store": "Continente",
    "price": 2.54,
    "category": "Snacks",
    "brand": "GoGo squeeZ"
  },
  {
    "id": "supersave-17267361",
    "name": "Pão de Cereais Fatiado sem Glúten emb. 360 gr",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwbce1fbce/images/col/809/8093647-topshot.jpg?sw=500&sh=500",
    "store": "Continente",
    "price": 5.49,
    "category": "Padaria",
    "brand": "Museu do Pão"
  },
  {
    "id": "supersave-17267360",
    "name": "Pão Integral Alemão de Centeio Biológico emb. 500 gr",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dweaa464fb/images/col/729/7290359-frente.jpg",
    "store": "Continente",
    "price": 3,
    "category": "Padaria",
    "brand": "Pema"
  },
  {
    "id": "supersave-17267359",
    "name": "Brioche Entrançado com Pepitas de Chocolate emb. 400 gr",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw312e46e3/images/col/801/8017742-frente.jpg?sw=500&sh=500",
    "store": "Continente",
    "price": 4.69,
    "category": "Padaria",
    "brand": "La Fournée Dorée"
  },
  {
    "id": "supersave-17267358",
    "name": "Pão Integral Alemão de Centeio emb. 500 gr",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwb2493ab0/images/col/729/7290362-frente.jpg",
    "store": "Continente",
    "price": 2.85,
    "category": "Padaria",
    "brand": "Pema"
  },
  {
    "id": "supersave-17267357",
    "name": "Pão Integral Alemão de Centeio com Sementes de Linho emb. 500 gr",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw922c0a41/images/col/729/7290380-frente.jpg",
    "store": "Continente",
    "price": 2.64,
    "category": "Padaria",
    "brand": "Pema"
  },
  {
    "id": "supersave-17267356",
    "name": "Rolinhos de Chocolate emb. 300 gr (6 un)",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw33f67604/images/col/801/8017738-frente.jpg?sw=500&sh=500",
    "store": "Continente",
    "price": 3.49,
    "category": "Padaria",
    "brand": "La Fournée Dorée"
  },
  {
    "id": "supersave-17267354",
    "name": "Pão de Trigo da Serra da Estrela Fatiado emb. 450 gr",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dwa62cf539/images/col/361/3610559-frente.jpg",
    "store": "Continente",
    "price": 2.19,
    "category": "Padaria",
    "brand": "Museu do Pão"
  },
  {
    "id": "supersave-17267333",
    "name": "Pão de Forma Clássico Branco sem Glúten emb. 350 gr",
    "imageUrl": "https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw47fdbce6/images/col/710/7102759-frente.jpg",
    "store": "Continente",
    "price": 2.49,
    "category": "Padaria",
    "brand": "Continente"
  }
];

export function getRandomProducts(count: number): Product[] {
  const shuffled = [...products].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export default products;
